name: release

on:
  push:
    branches:
    - main

jobs:
  goreleaser:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: reattach HEAD to Head Ref
        # b/c checkout action leaves in detached head state https://github.com/actions/checkout/issues/6
        run: git checkout "$(echo ${{ github.head_ref }})"
        if: github.head_ref != ''
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install node dedendencies
        run: npm i
      - name: Run node.js build
        run: npm run build
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --rm-dist
      - name: set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Publish release'
            git push
          fi
