name: release

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'build/**'

jobs:
  goreleaser:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ROBOT_MAC_FC_TOKEN }}
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install node dedendencies
        run: npm i
      - name: Run node.js build
        run: npm run build
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --rm-dist
      - name: set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_MAC_FC_TOKEN }}
          GITHUB_ACTOR_NAME: "@robot-mac-fc"
          GITHUB_ACTOR_EMAIL: "robot-mac-fc@users.noreply.github.com"
        run: |
          git config --global user.name "${GITHUB_ACTOR_NAME}"
          git config --global user.email "${GITHUB_ACTOR_EMAIL}"
      - name: commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Publish release'
            git push
          fi
